###
GET https://localhost:44330/api/Employee HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJOYW1lIjoiQWRtaW5pc3RyYWRvciIsIm5hbWVtYWlsIjoiQWRtaW5pc3RyYWRvciIsImp0aSI6IjgxZjI0OGJhLTNlMWMtNGJkZS1iNWNkLTNiMTJjNzA5OTAzMSIsIm5iZiI6MTcyNzQ2NzY2NSwiZXhwIjoxNzI3NTAzMTk5LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDMzMC8iLCJhdWQiOiJQdWJsaWMifQ.Dm05pZRtG2OZOlH5mr4NDFPHVsllhS4o-ZNfxit7Rd0

###
GET https://localhost:44330/api/Employee/id?id=71c9c900-449a-4ca9-8c5c-08dc9403f008 HTTP/1.1

###
POST https://localhost:44330/api/Employee HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJOYW1lIjoiQWRtaW5pc3RyYWRvciIsIm5hbWVtYWlsIjoiQWRtaW5pc3RyYWRvciIsImp0aSI6IjgxZjI0OGJhLTNlMWMtNGJkZS1iNWNkLTNiMTJjNzA5OTAzMSIsIm5iZiI6MTcyNzQ2NzY2NSwiZXhwIjoxNzI3NTAzMTk5LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDMzMC8iLCJhdWQiOiJQdWJsaWMifQ.Dm05pZRtG2OZOlH5mr4NDFPHVsllhS4o-ZNfxit7Rd0

{
  "id": null,
  "name": "Test",
  "firstName": "Test",
  "seconLastName": "Test",
  "fullName": "Test",
  "dateAcces": "2024-06-24T04:12:58.925Z",
  "birthDate": "2000-06-24T04:12:58.925Z",
  "age": 0,
  "fotography": "Test",
  "position": "Test",
  "salary": 0
}

###
PUT https://localhost:44330/api/Employee/71c9c900-449a-4ca9-8c5c-08dc9403f008/id HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJOYW1lIjoiQWRtaW5pc3RyYWRvciIsIm5hbWVtYWlsIjoiQWRtaW5pc3RyYWRvciIsImp0aSI6IjgxZjI0OGJhLTNlMWMtNGJkZS1iNWNkLTNiMTJjNzA5OTAzMSIsIm5iZiI6MTcyNzQ2NzY2NSwiZXhwIjoxNzI3NTAzMTk5LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo0NDMzMC8iLCJhdWQiOiJQdWJsaWMifQ.Dm05pZRtG2OZOlH5mr4NDFPHVsllhS4o-ZNfxit7Rd0

{
      "id": "71c9c900-449a-4ca9-8c5c-08dc9403f008",
      "name": "edit",
      "firstName": "edit",
      "seconLastName": "edit",
      "fullName": "edit edit edit",
      "dateAcces": "2024-06-24T04:12:58.925",
      "birthDate": "1999-06-24T04:12:58.925",
      "age": 0,
      "fotography": "edit",
      "fk_Position":"3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "positionName": "hr",
      "salary": 34.00
}
